name: Run Tests on PR to dev

on:
  pull_request:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Stellen Sie sicher, dass Sie eine requirements.txt Datei haben
    - name: Run tests
      run: pytest  # Oder Ihr spezifischer Befehl zum Ausführen von Tests
